return PlaceObj('ModDef', {
	'title', "Extended Research Pack",
	'description', "Adds a number of technologies to be researched in the game.",
	'image', "SteamPreviewImage.jpg",
	'last_changes', "Updated the mod to support the latest game version.\r\nAll techs seem to be working fine.",
	'id', "RprEy6",
	'steam_id', "1348093133",
	'author', "Witcher",
	'version', 147,
	'lua_revision', 238455,
	'code', {"Code/EventDrivenArchitectureEffect.lua"},
	'saved', 1543691870,
	'TagGameplay', true,
	'TagResearch', true,
})